# Generated by Django 5.2.6 on 2025-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Teléfono"),
        ),
    ]
