# Generated by Django 5.2.6 on 2025-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_rename_custommanager_managerdata_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Ubicación"
            ),
        ),
    ]
