# Generated by Django 5.2.6 on 2025-10-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_rename_decription_notification_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managerdata",
            name="acc_level",
            field=models.CharField(
                choices=[
                    ("principiante", "Principiante"),
                    ("intermedio", "Intermedio"),
                    ("avanzado", "Avanzado"),
                    ("experto", "Experto"),
                    ("maestro", "Maestro"),
                ],
                default="principiante",
                max_length=20,
                verbose_name="Nivel de Cuenta",
            ),
        ),
    ]
