# Generated by Django 5.2.6 on 2025-09-29 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="Puntos")),
                (
                    "acc_level",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronce"),
                            ("silver", "Plata"),
                            ("gold", "Oro"),
                            ("platinum", "Platino"),
                            ("diamond", "Diamante"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="Nivel de Cuenta",
                    ),
                ),
                (
                    "notifications",
                    models.IntegerField(default=0, verbose_name="Notificaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
                "ordering": ["-points", "-created_at"],
            },
        ),
    ]
