# Generated by Django 5.2.6 on 2025-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_project_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="decription",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
    ]
