# Generated by Django 5.2.6 on 2025-10-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_notification_decription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="decription",
            new_name="description",
        ),
    ]
