# Generated by Django 5.2.12 on 2026-03-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_client_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
